mothur_bin: /nfs/turbo/schloss-lab/bin/mothur-1.42.0/mothur
input_dir: data
datasets:
- soil
weights:
- none
db_version: v132
subsample_test: True
subsample_size: 1000
iterations: 2
replicates: 2
dataset-as-reference: False
silva-as-reference: True
