mothur_bin: /nfs/turbo/schloss-lab/bin/mothur-1.42.0/mothur
input_dir: data
datasets:
- soil
weights:
- none
- ref-abundance
- sample-abundance
- sample-dists
db_version: v132
subsample_test: False
subsample_size: 1000
iterations: 10
replicates: 10
dataset-as-reference: True
silva-as-reference: True
