mothur_bin: /nfs/turbo/schloss-lab/bin/mothur-1.42.0/mothur
input_dir: data
subsample_test: True
subsample_size: 1000
dataset-as-reference: True
silva-as-reference: False
silva_db_version: v132
datasets:
- soil
weights:
- none
- sample-dists
methods:
- open
- closed
printrefs:
- f
- t
reference_fractions:
    start: 50
    stop: 60
    step: 10
iterations: 10
replicates: 10
