mothur_bin: /nfs/turbo/schloss-lab/bin/mothur-1.42.0/mothur
subsample_test: False
subsample_size: 1000
datasets:
- human
- marine
- mouse
- soil
weights:
- none
- ref-abundance
- sample-abundance
- sample-dists
methods:
- open
- closed
printrefs:
- t
- f
reference_fractions:
    start: 10
    stop: 100
    step: 10
seeds: 10
