cluster: "pbs-torque/pbs-submit.py -N {cluster.jobname} -A {cluster.account} -q {cluster.queue} -l qos=flux,procs={cluster.procs},mem={cluster.mem},walltime={cluster.walltime} -M {cluster.email} -m {mailon} -j {cluster.jobout} -V -o {cluster.outdir} "
cluster-status: "pbs-status.py"
jobscript: "pbs-jobscript.sh"
jobs: 5000
immediate-submit: False
verbose: true
notemp: true
cluster-config: "cluster.json"
