datasets:
- marine
- mouse
- soil
references:
- silva
weights:
- simple
methods:
- de_novo
- open
- closed
printrefs:
- f
ref_fracs:
    start: 5
    stop: 6
    step: 1
seeds: 4
configpath: 'config/config_test.yaml'
