datasets:
- human
- marine
- mouse
- soil
references:
- silva
- gg
- rdp
weights:
- simple
- abundance
- distance
methods:
- open
- closed
printrefs:
- f
reference_fractions:
    start: 10
    stop: 100
    step: 10
seeds: 100
