datasets:
- human
- marine
- mouse
- soil
references:
- silva
- rdp
- gg
weights:
- simple
- abundance
- distance
methods:
- open
- closed
printrefs:
- f
ref_fracs:
    start: 1
    stop: 10
    step: 1
seeds: 100
configpath: 'config/config.yaml'
