mothur_bin: /nfs/turbo/schloss-lab/bin/mothur-1.42.0/mothur
input_dir: data
subsample_test: False
subsample_size: 1000
workflows:
    dataset-as-reference: False
    silva-as-reference: True
silva_db_version: v132
datasets:
- soil
weights:
- none
- ref-abundance
- sample-abundance
- sample-dists
methods:
- open
- closed
printrefs:
- t
- f
reference_fractions:
    start: 10
    stop: 100
    step: 10
iterations: 10
replicates: 10
