algorithm:
  cap: \textbf{The OptiFit Algorithm.}
       TODO write this caption.
  dim: c(6.87,5.5)
  path: here('figures', 'algorithm.tiff')
workflow:
  cap: \textbf{The Analysis Workflow.}
       Reference sequences from Greengenes, the RDP, and SILVA were downloaded,
       preprocessed with mothur by trimming to the V4 region, and clustered _de
       novo_ with OptiClust for 100 repetitions.
       Datasets from human, marine, mouse, and soil microbiomes were
       downloaded, preprocessed with mothur by aligning to the SILVA V4
       reference alignment, then clustered _de novo_ with OptiClust for 100
       repetitions.
       Individual datasets were fit to reference databases with OptiFit;
       OptiFit was repeated 100 times for each dataset and database combination.
       Datasets were also randomly split into a reference and query fraction,
       and the query sequences were fit to the reference sequences with OptiFit
       for 100 repetitions.
       The final MCC score was reported for all OptiClust and OptiFit
       repetitions.
  dim: c(6,4)
  path: here('figures', 'workflow.tiff')
results_sum:
  cap: \textbf{Benchmarking Results.}
       The median MCC score, fraction of query sequences that mapped in
       closed-reference clustering, and runtime in seconds from repeating each
       clustering method 100 times.
       Each dataset underwent _de novo_ clustering using OptiClust or
       reference-based clustering using OptiFit with one of two strategies;
       splitting the dataset and fitting 50% the sequences to the other 50%, or
       fitting the dataset to a reference database (Greengenes, SILVA, or RDP).
       Reference-based clustering was repeated with open and closed mode.
       For additional comparison, VSEARCH was used for _de novo_ and reference-based clustering against the Greengenes database.
  dim: c(6,6)
  path: here('figures', 'results_sum.tiff')
results_split:
  cap: \textbf{Split dataset strategy.}
       The median MCC score, fraction of query sequences that mapped in
       closed-reference clustering, and runtime in seconds from repeating each
       clustering method 100 times.
       Each dataset was split into a reference and query fraction.
       References sequences were selected via a simple random sample, weighting
       sequences by relative abundance, or weighting by similarity to other
       sequences in the dataset.
       With the simple random sample method, dataset splitting was repeated
       with reference fractions ranging from 10% to 90% of the dataset and for
       100 random seeds.
       _De novo_ clustering each dataset is also shown for comparison.
  dim: c(6.87,8)
  path: here('figures', 'results_split.tiff')
