algorithm:
  cap: \textbf{The OptiFit Algorithm.}
       TODO write this caption.
  path: here('figures', 'algorithm.tiff')
  dim: c(6.8,9)
workflow:
  cap: \textbf{The Analysis Workflow.}
       Reference sequences from Greengenes, the RDP, and SILVA were downloaded, trimmed to the V4 region using mothur, and clustered _de novo_ with OptiClust for 100 repetitions.
       Datasets from human, marine, mouse, and soil microbiomes were downloaded, aligned to the SILVA reference alignment and trimmed with mothur, then clustered _de novo_ with OptiClust for 100 repetitions.
       Individual datasets were fit to reference databases with OptiFit; OptiFit was repeated 100 times for each dataset and database combination.
       Datasets were also randomly split into a reference and query fraction, and the query sequences were fit to the reference sequences with OptiFit for 100 repetitions.
       The final MCC score was reported for all OptiClust and OptiFit repetitions.
  path: here('figures', 'workflow.tiff')
  dim: c(6,4)
results_sum:
  cap: \textbf{Benchmarking Results.}
       TODO write this caption.
  path: here('figures', 'results_sum.tiff')
  dim: c(6,6)
results_split:
  cap: \textbf{Split dataset strategy.}
       TODO write this caption.
  path: here('figures', 'results_split.tiff')
  dim: c(6,9)
