algorithm:
  cap: \textbf{The OptiFit Algorithm.}
       TODO write this caption.
  path: here('figures', 'algorithm.tiff')
  dim: c(4,4)
workflow:
  cap: \textbf{The Analysis Workflow.}
       Reference sequences from Greengenes, the RDP, and SILVA were downloaded,
       preprocessed with mothur by trimming to the V4 region, and clustered _de
       novo_ with OptiClust for 100 repetitions.
       Datasets from human, marine, mouse, and soil microbiomes were
       downloaded, preprocessed with mothur by aligning to the SILVA V4
       reference alignment, then clustered _de novo_ with OptiClust for 100
       repetitions.
       Individual datasets were fit to reference databases with OptiFit;
       OptiFit was repeated 100 times for each dataset and database combination.
       Datasets were also randomly split into a reference and query fraction,
       and the query sequences were fit to the reference sequences with OptiFit
       for 100 repetitions.
       The final MCC score was reported for all OptiClust and OptiFit
       repetitions.
  path: here('figures', 'workflow.tiff')
  dim: c(6,4)
results_sum:
  cap: \textbf{Benchmarking Results.}
       TODO write this caption.
  path: here('figures', 'results_sum.tiff')
  dim: c(6.875,6.875)
results_split:
  cap: \textbf{Split dataset strategy.}
       TODO write this caption.
  path: here('figures', 'results_split.tiff')
  dim: c(6.875,9.0625)
